### ISSUE TITLE
日程を決める

### ISSUE THREAD

**Issue by dot** [tokairb/nagoyark03#2]
- [x] 9/5,6
- [ ] 9/12,13 12: RailsGirls神戸
- [x] 9/19,20
- [x] 9/26,27
- [x] 10/3,4
- [x] 10/10,11
- [ ] 10/17,18 17:みうらさんNG
- [x] 10/24,25
- [x] 10/31,11/1
- [ ] 11/7,8 8:大江戸RK
- [ ] 11/14,15 14:みうらさんNG
- [x] 11/21,22
- [x] 11/28,29

**Comment by dot** [comment]
9-12月で、他のイベントの日程を調べる。

**Comment by dot** [comment]
- 大江戸Ruby会議05 11/08
- RubyKaigi2015 12/11-13
- RubyWorldConf 2015 11/12-13

**Comment by yada-ITA** [comment]
RailsGirls系の追加です。
- RailsGirls Kobe 9/11-12

**Comment by dot** [comment]
* [ ] 9/5,6
* [ ] 9/12,13 12: RailsGirls神戸
* [ ] 9/19,20
* [ ] 9/26,27
* [ ] 10/3,4
* [ ] 10/10,11
* [ ] 10/17,18 17:みうらさんNG
* [ ] 10/24,25
* [ ] 10/31,11/1
* [ ] 11/7,8 8:大江戸RK
* [ ] 11/14,15 14:みうらさんNG
* [ ] 11/21,22
* [ ] 11/28,29

**Comment by dot** [comment]
2-3この候補に絞りたい

**Comment by dot** [comment]
#1 に伴い 2/27(土) となりました。
